#!/usr/bin/env python3
"""MCPScope Phase-1, Day 1 AM: automated competitor sweep + name check.

Searches GitHub and npm for existing MCP proxy/inspector/observability tools and
checks whether the names `mcpscope` are still free on PyPI / npm / GitHub.
Writes a markdown report to reports/competitor_sweep.md (and prints a summary).

Usage:  .venv/bin/python validation_mcpscope/competitor_sweep.py
Optional: GITHUB_TOKEN env var raises the GitHub search rate limit (10 -> 30/min).

This automates the "30-min competitor sweep"; the hands-on audit of the official
MCP Inspector (npx @modelcontextprotocol/inspector) is still yours to do.
"""
import os
import sys
import time
from datetime import datetime
from pathlib import Path

import requests

GITHUB_QUERIES = [
    "mcp proxy",
    "mcp inspector",
    "mcp traffic monitor",
    "mcp observability",
    "mcp debugger tool calls",
]
NPM_QUERIES = ["mcp proxy", "mcp inspector", "mcp observability"]
NAME = "mcpscope"
UA = {"User-Agent": "mcpscope-validation/0.1"}
OUT = Path(__file__).resolve().parent.parent / "reports" / "competitor_sweep.md"


def gh_headers():
    h = dict(UA, Accept="application/vnd.github+json")
    tok = os.getenv("GITHUB_TOKEN")
    if tok:
        h["Authorization"] = "Bearer " + tok
    return h


def github_repos(query, per_page=8):
    """Top repos for a query, by stars. Returns [] on rate-limit/error."""
    try:
        r = requests.get(
            "https://api.github.com/search/repositories",
            params={"q": query, "sort": "stars", "order": "desc",
                    "per_page": per_page},
            headers=gh_headers(), timeout=20)
        if r.status_code == 403:
            print("  ! GitHub rate-limited on %r — waiting 60s" % query)
            time.sleep(60)
            return github_repos(query, per_page)
        r.raise_for_status()
        out = []
        for it in r.json().get("items", []):
            out.append({
                "name": it.get("full_name"),
                "stars": it.get("stargazers_count", 0),
                "desc": (it.get("description") or "")[:140],
                "pushed": (it.get("pushed_at") or "")[:10],
                "url": it.get("html_url"),
            })
        return out
    except requests.RequestException as e:
        print("  ! GitHub search failed (%s): %s" % (query, e))
        return []


def npm_search(query, size=8):
    try:
        r = requests.get(
            "https://registry.npmjs.org/-/v1/search",
            params={"text": query, "size": size}, headers=UA, timeout=20)
        r.raise_for_status()
        out = []
        for obj in r.json().get("objects", []):
            p = obj.get("package", {})
            out.append({
                "name": p.get("name"),
                "desc": (p.get("description") or "")[:140],
                "date": (p.get("date") or "")[:10],
                "url": (p.get("links") or {}).get("npm", ""),
            })
        return out
    except requests.RequestException as e:
        print("  ! npm search failed (%s): %s" % (query, e))
        return []


def name_taken(url):
    """True/False/None(unknown)."""
    try:
        return requests.get(url, headers=UA, timeout=15).status_code == 200
    except requests.RequestException:
        return None


def fmt(taken):
    return {True: "TAKEN", False: "free ✅", None: "?"}[taken]


def main():
    lines = ["# Competitor sweep — %s" % datetime.now().strftime("%Y-%m-%d %H:%M"),
             "", "Auto-generated by validation_mcpscope/competitor_sweep.py.",
             "Star/recency are the signal: high-star + recently-pushed = real competitor.",
             ""]

    print("Checking name availability for %r ..." % NAME)
    avail = {
        "PyPI": name_taken("https://pypi.org/pypi/%s/json" % NAME),
        "npm": name_taken("https://registry.npmjs.org/%s" % NAME),
        "GitHub org/user": name_taken("https://api.github.com/users/%s" % NAME),
    }
    lines += ["## Name availability: `%s`" % NAME, ""]
    for k, v in avail.items():
        line = "- %s: %s" % (k, fmt(v))
        lines.append(line)
        print(" ", line)
    lines.append("")

    lines += ["## GitHub repos", ""]
    seen = set()
    for q in GITHUB_QUERIES:
        print("GitHub: %r ..." % q)
        hits = github_repos(q)
        fresh = [h for h in hits if h["name"] not in seen]
        seen.update(h["name"] for h in fresh)
        if fresh:
            lines.append("### `%s`" % q)
            for h in sorted(fresh, key=lambda x: -x["stars"]):
                lines.append("- **%s** (⭐%d, pushed %s) — %s  <%s>" % (
                    h["name"], h["stars"], h["pushed"], h["desc"], h["url"]))
            lines.append("")
        time.sleep(7)  # stay under the unauth search rate limit

    lines += ["## npm packages", ""]
    seen_npm = set()
    for q in NPM_QUERIES:
        print("npm: %r ..." % q)
        for h in npm_search(q):
            if h["name"] in seen_npm:
                continue
            seen_npm.add(h["name"])
            lines.append("- **%s** (%s) — %s  <%s>" % (
                h["name"], h["date"], h["desc"], h["url"]))
    lines += ["", "## Verdict (fill in by hand)", "",
              "- Direct live-proxy competitors found: ",
              "- Strongest one and why it does/doesn't kill the wedge: ",
              "- Gate impact (gaps still >= 4?): "]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("\nReport written to %s" % OUT)


if __name__ == "__main__":
    sys.exit(main())
